### ISSUE TITLE
Check if physics works when building to WebGL

### ISSUE THREAD

**Issue by Malmis1** [Malmis1/Recoil-Runner#16]
Ensure that the physics after building to WebGL works as intended.

**Comment by 09ejacob** [comment]
![image](https://github.com/user-attachments/assets/d92e0b3b-74dd-4d93-a983-3481d3fd50a0)
Building with WebGl did not work. We have to fix this

**Comment by Malmis1** [comment]
I just fixed the project not building to WebGL 3f944a4. But we need to test how the gameplay and physics feel, to make sure that they are not different when using WebGL.

**Comment by Malmis1** [comment]
I have tested some on my level and it looks passable. Feel free to reopen this issue if any problems arises when trying the game on WebGL.
