### ISSUE TITLE
Add enemy counter/kill count

### ISSUE THREAD

**Issue by Malmis1** [Malmis1/Recoil-Runner#29]
Add a counter that says how many enemies the player has defeated, and enemies total that are in the level.

**Comment by UlrikRibler** [comment]
Kill counter added, missing backround styling and change of coulour on the font to fit the game

**Comment by Malmis1** [comment]
Make the kill counter say how many kills remain in the current level. Have it say something like 3/5 kills when the player has defeated 3 enemies out of 5 in a level.

Also make sure to make a kill count *per level*.
